name: build-splus

run-name: ${{ github.actor }} - php-caddy Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    needs: [ build-frontend ]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build -t n3rv4/php-caddy .

      - name: Push the new Docker image
        run: docker push n3rv4/php-caddy
